---
title: "Mapping Homicide Trends in Boston, MA"
subtitle: "Homework 5 (option 1) | ERHS 535"
author: "Caroline Wendt"
date: "11/22/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.path = "figs/", echo = TRUE,
                      warning = FALSE, error = FALSE, message = FALSE)
```

```{r}
# packages
library(readr)
library(dplyr)
library(lubridate)
library(stringr)
library(forcats)
library(tigris)
library(sf)
library(ggplot2)
library(viridis)
library(ggdark)
```

```{r}
# get data
homicides <- read_csv("../data/data-homicides-master/homicide-data.csv") %>%
  # create new column called city_name to unite city and state
  tidyr::unite("city_name", c(city, state), sep = ", ")
```

```{r}
# filter to Boston, Massachusetts homicides
ma_homicides <- homicides %>% 
  filter(city_name == "Boston, MA") %>% 
  # create column for unsolved homicides
  mutate(unsolved_hom = 
           disposition %in% c("Closed without arrest","Open/No arrest"),
  # create column for top 3 victim race (lumps other races into "Other")
         victim_race_lump = fct_lump(victim_race, n = 3),
  # create new column with status
         solved_status = if_else(unsolved_hom == TRUE,
                                 "Unsolved", "Solved" ),
  # change reported_date to date class
         reported_date = ymd(reported_date),
  # extract year and make new column
         reported_year = str_sub(reported_date, 1, 4)) %>%
  # filter missing latitude and/or longitude coordinates
  filter(!is.na(lat), !is.na(lon))
```

```{r}
# download boundaries for sub-city geography (tracts) from tigris
# show as a layer underneath the points showing homicides
boston_tracts <- tracts(state = 25,
                        county = 025,
                        cb = TRUE,
                        class = "sf")
class(boston_tracts)
```


```{r}
# change to sf object; say which columns are the coordinates and set a CRS
boston_homicides <- st_as_sf(ma_homicides,
                             coords = c("lon", "lat")) %>%
  st_set_crs(4269)
```

```{r}
# check range of reported years for graph subtitle
range(ma_homicides$reported_year)
```

```{r}
# map plot of Boston homicides
ggplot() +
  geom_sf(data = boston_tracts, color = "black") +
  geom_sf(data = boston_homicides,
          aes(color = victim_race_lump, fill = victim_race_lump)) +
  scale_color_viridis(option = "plasma",
                     discrete = TRUE,
                     name = "Victim Race") +
  scale_fill_viridis(option = "plasma",
                     discrete = TRUE,
                     name = "Victim Race") +
  facet_grid(~ solved_status) +
  labs(title = "Boston Homicides by Victim Race",
       subtitle = "Suffolk County | 2007-2017") +
  dark_theme_linedraw() +
  ggplot2::theme(legend.position = "bottom",
                 plot.title = element_text(face = "bold"),
                 legend.title = element_text(face = "bold"),
                 strip.text.x = element_text(size = 10, color = "black",
                                             face = "bold"))
```

